# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
        pip install pyyaml
        pip install python-frontmatter
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run export python script
      run: |
        python python_script/infosPatternToJson.py
    - name: Git authentification
      run: |
        git config --global user.name "ntenieres-bib"
        git config --global user.email "nathan.tenieres@michelin.com"
    - name: Switching from HTTPS to SSH
      run: git remote set-url origin git@github.com:michelin/Evergreen-Patterns.git
    - name: Check for changes
      run: git status
    - name: Stage changed files
      run: git add .
    - name: Commit changed files
      run: git commit -m "Updating JSON file"
    - name: Fetch from master
      run: git fetch origin main
    #- name: Push code to master
     # run: git push origin main
      
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main 
